const http = require('http');

function makeRequest(path, method, body, token) {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : '';
    const headers = { 'Content-Type': 'application/json' };
    if (token) headers['Authorization'] = `Bearer ${token}`;

    const req = http.request(
      {
        hostname: 'localhost',
        port: 5000,
        path,
        method,
        headers,
      },
      (res) => {
        let resBody = '';
        res.on('data', (chunk) => (resBody += chunk));
        res.on('end', () => {
          try {
            resolve({ status: res.statusCode, body: JSON.parse(resBody) });
          } catch (_) {
            resolve({ status: res.statusCode, body: resBody });
          }
        });
      }
    );

    req.on('error', reject);
    if (data) req.write(data);
    req.end();
  });
}

async function runTests() {
  console.log('🧪 Starting SpeakUp Feature Validation Tests...\n');

  // 1. Login as user to get token
  const loginRes = await makeRequest('/api/auth/login', 'POST', {
    email: 'amina@speakup.ai',
    password: 'password123',
  });
  console.log(`[Test 1] Login: Status ${loginRes.status}, User: ${loginRes.body.data?.user?.name}`);
  const token = loginRes.body.token;

  // 2. Submit session for "The Coach" (How you say it logic: trembling, fear, sickness)
  const coachRes = await makeRequest(
    '/api/sessions/analyze',
    'POST',
    {
      evaluatorId: 'coach',
      evaluatorName: 'The Coach',
      categoryId: 'tech',
      topic: 'AI and Future of Work',
      durationSeconds: 180,
      transcript: 'I believe that AI will transform industries, but my voice felt hesitant during the opening remarks.',
      moduleType: 'lounge',
    },
    token
  );
  console.log(`[Test 2] Coach Evaluation: Status ${coachRes.status}, Score: ${coachRes.body.data?.overallScore}`);
  console.log('  Audience Questions generated by Coach:');
  const coachQuestions = coachRes.body.data?.audienceQuestions || [];
  coachQuestions.forEach((q, i) => console.log(`    Q${i + 1}: ${q.question}`));

  // 3. Submit session for "The Executive" (What you say logic: facts, metrics, logic)
  const execRes = await makeRequest(
    '/api/sessions/analyze',
    'POST',
    {
      evaluatorId: 'executive',
      evaluatorName: 'The Executive',
      categoryId: 'tech',
      topic: 'Quarterly Cloud Migration ROI',
      durationSeconds: 300,
      transcript: 'Our migration project achieved a 38 percent drop in infrastructure overhead and reduced latency by 120 milliseconds.',
      moduleType: 'boardroom',
    },
    token
  );
  console.log(`\n[Test 3] Executive Evaluation: Status ${execRes.status}, Score: ${execRes.body.data?.overallScore}`);
  console.log('  Audience Questions generated by Executive:');
  const execQuestions = execRes.body.data?.audienceQuestions || [];
  execQuestions.forEach((q, i) => console.log(`    Q${i + 1}: ${q.question}`));

  // 4. Submit session for "The Stage Evaluator" (Monologue: no questions)
  const stageRes = await makeRequest(
    '/api/sessions/analyze',
    'POST',
    {
      evaluatorId: 'stage',
      evaluatorName: 'The Stage Keynote Mentor',
      categoryId: 'keynote',
      topic: 'Inspiring Change in Tech',
      durationSeconds: 600,
      transcript: 'Today I stand before you to discuss the spark of human courage and creativity.',
      moduleType: 'auditorium',
    },
    token
  );
  console.log(`\n[Test 4] Stage Evaluator: Status ${stageRes.status}, Questions count: ${stageRes.body.data?.audienceQuestions?.length}`);

  // 5. Update oral Q&A answers on Coach session
  const sessionId = coachRes.body.data?.id;
  if (sessionId) {
    const updatedQA = [
      {
        question: coachQuestions[0]?.question || 'Are you feeling nervous or afraid?',
        speakerAnswer: 'I felt initial nervousness before stepping up, but diaphragmatic breathing helped me settle.',
      },
      {
        question: coachQuestions[1]?.question || 'Why did your voice tremble during the opening?',
        speakerAnswer: 'My voice had a brief tremble due to dry throat, which I resolved with steady breath pacing.',
      },
    ];
    const updateRes = await makeRequest(`/api/sessions/${sessionId}/qa`, 'PUT', { audienceQuestions: updatedQA }, token);
    console.log(`\n[Test 5] Update Oral Q&A Answers (PUT /sessions/${sessionId}/qa): Status ${updateRes.status}`);
    console.log('  Saved oral answers:', updateRes.body.data?.audienceQuestions?.map((q) => q.speakerAnswer));
  }

  // 6. Verify session history contains saved sessions
  const historyRes = await makeRequest('/api/sessions/history', 'GET', null, token);
  console.log(`\n[Test 6] User Session History: Status ${historyRes.status}, Total Saved: ${historyRes.body.count}`);

  console.log('\n✨ All Feature Validation Tests Completed Successfully!');
}

runTests().catch(console.error);
